#
# VanishNoPacket
#   A fine choice of invisibility for the discerning server administrator.
#   http://www.kitteh.org
#
#  See documentation for details:
#  http://dev.bukkit.org/server-mods/vanish/pages/configuration/
#
fakeannounce:
    automaticforsilentjoin: false
    join: '%p joined the game.'
    quit: '%p left the game.'
hooks:
    essentials: false
    dynmap: false
    JSONAPI: false
enableColoration: false
spoutcraft:
    enable: false
updates:
    check: true
permtest:
    enable: false